version: "3.8"
services:
  db:
    image: postgres:15
    container_name: avito_pvz_db
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - ./migrations:/migrations:ro

  migrator:
    image: postgres:15
    depends_on: [ db ]
    volumes:
      - ./migrations:/migrations:ro
    # ждём пару секунд, затем последовательно применяем *.sql
    entrypoint: [ "bash", "-c",
      "sleep 5 && \
        for f in /migrations/*.sql; do echo applying $f; psql -h db -U master -d master -f $f; done" ]
    environment:
      PGPASSWORD: master